/**
 * @type {Record.<string, Promise<{default: string}>>}
 */
export const cardImages = {
	"back": import("$lib/images/cards/CARD-BACK-BLACK.svg?raw"),
	"AxC": import("$lib/images/cards/CLUB-1.svg?raw"),
	"2xC": import("$lib/images/cards/CLUB-2.svg?raw"),
	"3xC": import("$lib/images/cards/CLUB-3.svg?raw"),
	"4xC": import("$lib/images/cards/CLUB-4.svg?raw"),
	"5xC": import("$lib/images/cards/CLUB-5.svg?raw"),
	"6xC": import("$lib/images/cards/CLUB-6.svg?raw"),
	"7xC": import("$lib/images/cards/CLUB-7.svg?raw"),
	"8xC": import("$lib/images/cards/CLUB-8.svg?raw"),
	"9xC": import("$lib/images/cards/CLUB-9.svg?raw"),
	"10xC": import("$lib/images/cards/CLUB-10.svg?raw"),
	"JxC": import("$lib/images/cards/CLUB-11-JACK.svg?raw"),
	"QxC": import("$lib/images/cards/CLUB-12-QUEEN.svg?raw"),
	"KxC": import("$lib/images/cards/CLUB-13-KING.svg?raw"),
	"AxD": import("$lib/images/cards/DIAMOND-1.svg?raw"),
	"2xD": import("$lib/images/cards/DIAMOND-2.svg?raw"),
	"3xD": import("$lib/images/cards/DIAMOND-3.svg?raw"),
	"4xD": import("$lib/images/cards/DIAMOND-4.svg?raw"),
	"5xD": import("$lib/images/cards/DIAMOND-5.svg?raw"),
	"6xD": import("$lib/images/cards/DIAMOND-6.svg?raw"),
	"7xD": import("$lib/images/cards/DIAMOND-7.svg?raw"),
	"8xD": import("$lib/images/cards/DIAMOND-8.svg?raw"),
	"9xD": import("$lib/images/cards/DIAMOND-9.svg?raw"),
	"10xD": import("$lib/images/cards/DIAMOND-10.svg?raw"),
	"JxD": import("$lib/images/cards/DIAMOND-11-JACK.svg?raw"),
	"QxD": import("$lib/images/cards/DIAMOND-12-QUEEN.svg?raw"),
	"KxD": import("$lib/images/cards/DIAMOND-13-KING.svg?raw"),
	"AxH": import("$lib/images/cards/HEART-1.svg?raw"),
	"2xH": import("$lib/images/cards/HEART-2.svg?raw"),
	"3xH": import("$lib/images/cards/HEART-3.svg?raw"),
	"4xH": import("$lib/images/cards/HEART-4.svg?raw"),
	"5xH": import("$lib/images/cards/HEART-5.svg?raw"),
	"6xH": import("$lib/images/cards/HEART-6.svg?raw"),
	"7xH": import("$lib/images/cards/HEART-7.svg?raw"),
	"8xH": import("$lib/images/cards/HEART-8.svg?raw"),
	"9xH": import("$lib/images/cards/HEART-9.svg?raw"),
	"10xH": import("$lib/images/cards/HEART-10.svg?raw"),
	"JxH": import("$lib/images/cards/HEART-11-JACK.svg?raw"),
	"QxH": import("$lib/images/cards/HEART-12-QUEEN.svg?raw"),
	"KxH": import("$lib/images/cards/HEART-13-KING.svg?raw"),
	"AxS": import("$lib/images/cards/SPADE-1.svg?raw"),
	"2xS": import("$lib/images/cards/SPADE-2.svg?raw"),
	"3xS": import("$lib/images/cards/SPADE-3.svg?raw"),
	"4xS": import("$lib/images/cards/SPADE-4.svg?raw"),
	"5xS": import("$lib/images/cards/SPADE-5.svg?raw"),
	"6xS": import("$lib/images/cards/SPADE-6.svg?raw"),
	"7xS": import("$lib/images/cards/SPADE-7.svg?raw"),
	"8xS": import("$lib/images/cards/SPADE-8.svg?raw"),
	"9xS": import("$lib/images/cards/SPADE-9.svg?raw"),
	"10xS": import("$lib/images/cards/SPADE-10.svg?raw"),
	"JxS": import("$lib/images/cards/SPADE-11-JACK.svg?raw"),
	"QxS": import("$lib/images/cards/SPADE-12-QUEEN.svg?raw"),
	"KxS": import("$lib/images/cards/SPADE-13-KING.svg?raw"),
}
