services:
  client:
    build:
      context: ./bring-ten/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://server:8080
    restart: unless-stopped

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ORIGIN=http://client:3000
    restart: unless-stopped
