services:
  client:
    build:
      context: ./bring-ten/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ORIGIN=http://165.227.221.32:3000
    restart: unless-stopped

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ORIGINS=http://localhost:3000,http://165.227.221.32:3000
    restart: unless-stopped
